# Generated by Django 6.0.5 on 2026-07-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='required_department',
            field=models.ForeignKey(blank=True, help_text='Department allowed to complete this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='required_role',
            field=models.CharField(blank=True, help_text='Role allowed to complete this workflow step.', max_length=20, null=True),
        ),
    ]
